export const DeviceInfos = [
  {
    id: "1",
    name: "iPhone (original)",
    year: 2007,
    screenSize: "3.5 inches",
    imageUrl: require("./assets/original.jpeg"),
    imageUrl1: require("./assets/second/ori.jpeg"),
    storage: "16GB",
    color: "Black",
    chip: "Apple A4",
    sensors: "Accelerometer, Proximity",
    sim: "Nano-SIM",
  },
  {
    id: "2",
    name: "iPhone 3G",
    year: 2008,
    screenSize: "3.5 inches",
    imageUrl: require("./assets/3g.jpeg"),
    imageUrl1: require("./assets/second/3.webp"),
    storage: "8GB, 16GB",
    color: "Black, White",
    chip: "Apple A-GPS",
    sensors: "Accelerometer, Proximity",
    sim: "Mini-SIM",
  },
  {
    id: "3",
    name: "iPhone 3GS",
    year: 2009,
    screenSize: "3.5 inches",
    imageUrl: require("./assets/3gs.jpeg"),
    imageUrl1: require("./assets/second/3.webp"),
    storage: "8GB, 16GB, 32GB",
    color: "Black, White",
    chip: "Apple A-GPS",
    sensors: "Accelerometer, Proximity, Compass",
    sim: "Micro-SIM",
  },
  {
    id: "4",
    name: "iPhone 4",
    year: 2010,
    screenSize: "3.5 inches",
    imageUrl: require("./assets/4.jpeg"),
    imageUrl1: require("./assets/second/4.jpeg"),
    storage: "8GB, 16GB, 32GB",
    color: "Black, White",
    chip: "Apple A4",
    sensors: "Accelerometer, Proximity, Gyroscope, Ambient light",
    sim: "Micro-SIM",
  },
  {
    id: "5",
    name: "iPhone 4s",
    year: 2011,
    screenSize: "3.5 inches",
    imageUrl: require("./assets/4s.jpeg"),
    imageUrl1: require("./assets/second/4.jpeg"),
    storage: "8GB, 16GB, 32GB, 64GB",
    color: "Black, White",
    chip: "Apple A5",
    sensors: "Accelerometer, Proximity, Gyroscope, Ambient light, Compass",
    sim: "Micro-SIM",
  },
  {
    id: "6",
    name: "iPhone 5",
    year: 2012,
    screenSize: "4 inches",
    imageUrl: require("./assets/5.jpeg"),
    imageUrl1: require("./assets/second/5.webp"),
    storage: "16GB, 32GB, 64GB",
    color: "Black, White",
    chip: "Apple A6",
    sensors: "Accelerometer, Proximity, Gyroscope, Ambient light, Compass",
    sim: "Nano-SIM",
  },
  {
    id: "7",
    name: "iPhone 5c",
    year: 2013,
    screenSize: "4 inches",
    imageUrl: require("./assets/5c.jpeg"),
    imageUrl1: require("./assets/second/5.webp"),
    storage: "8GB, 16GB, 32GB",
    color: "White, Pink, Yellow, Blue, Green",
    chip: "Apple A6",
    sensors: "Accelerometer, Proximity, Gyroscope, Ambient light, Compass",
    sim: "Nano-SIM",
  },
  {
    id: "8",
    name: "iPhone 5s",
    year: 2013,
    screenSize: "4 inches",
    imageUrl: require("./assets/5s.jpeg"),
    imageUrl1: require("./assets/second/5.webp"),
    storage: "16GB, 32GB, 64GB",
    color: "Space Gray, Silver, Gold",
    chip: "Apple A7",
    sensors:
      "Accelerometer, Proximity, Gyroscope, Ambient light, Compass, Touch ID",
    sim: "Nano-SIM",
  },
  {
    id: "9",
    name: "iPhone 6",
    year: 2014,
    screenSize: "4.7 inches",
    imageUrl: require("./assets/6.jpeg"),
    imageUrl1: require("./assets/second/6.webp"),
    storage: "16GB, 64GB, 128GB",
    color: "Space Gray, Silver, Gold",
    chip: "Apple A8",
    sensors:
      "Accelerometer, Proximity, Gyroscope, Compass, Barometer, Touch ID",
    sim: "Nano-SIM",
  },
  {
    id: "10",
    name: "iPhone 6 Plus",
    year: 2014,
    screenSize: "5.5 inches",
    imageUrl: require("./assets/6plus.jpeg"),
    imageUrl1: require("./assets/second/6.webp"),
    storage: "16GB, 64GB, 128GB",
    color: "Space Gray, Silver, Gold",
    chip: "Apple A8",
    sensors:
      "Accelerometer, Proximity, Gyroscope, Compass, Barometer, Touch ID",
    sim: "Nano-SIM",
  },
  {
    id: "11",
    name: "iPhone 6s",
    year: 2015,
    screenSize: "4.7 inches",
    imageUrl: require("./assets/6s.jpeg"),
    imageUrl1: require("./assets/second/6.webp"),
    storage: "16GB, 32GB, 64GB, 128GB",
    color: "Space Gray, Silver, Gold, Rose Gold",
    chip: "Apple A9",
    sensors:
      "Accelerometer, Proximity, Gyroscope, Compass, Barometer, Touch ID",
    sim: "Nano-SIM",
  },
  {
    id: "12",
    name: "iPhone 6s Plus",
    year: 2015,
    screenSize: "5.5 inches",
    imageUrl: require("./assets/6splus.jpeg"),
    imageUrl1: require("./assets/second/6.webp"),
    storage: "16GB, 32GB, 64GB, 128GB",
    color: "Space Gray, Silver, Gold, Rose Gold",
    chip: "Apple A9",
    sensors:
      "Accelerometer, Proximity, Gyroscope, Compass, Barometer, Touch ID",
    sim: "Nano-SIM",
  },
  {
    id: "13",
    name: "iPhone SE ",
    year: 2016,
    screenSize: "4 inches",
    imageUrl: require("./assets/se1.jpeg"),
    imageUrl1: require("./assets/second/5.webp"),
    storage: "16GB, 32GB, 64GB, 128GB",
    color: "Space Gray, Silver, Gold, Rose Gold",
    chip: "Apple A9",
    sensors:
      "Accelerometer, Proximity, Gyroscope, Compass, Barometer, Touch ID",
    sim: "Nano-SIM",
  },
  {
    id: "14",
    name: "iPhone 7",
    year: 2016,
    screenSize: "4.7 inches",
    imageUrl: require("./assets/7.jpeg"),
    imageUrl1: require("./assets/second/7.jpeg"),
    storage: "32GB, 128GB, 256GB",
    color: "Black, Jet Black, Silver, Gold, Rose Gold, Red",
    chip: "Apple A10 Fusion",
    sensors:
      "Accelerometer, Proximity, Gyroscope, Compass, Barometer, Touch ID",
    sim: "Nano-SIM",
  },
  {
    id: "15",
    name: "iPhone 7 Plus",
    year: 2016,
    screenSize: "5.5 inches",
    imageUrl: require("./assets/7plus.jpeg"),
    imageUrl1: require("./assets/second/7.jpeg"),
    storage: "32GB, 128GB, 256GB",
    color: "Black, Jet Black, Silver, Gold, Rose Gold, Red",
    chip: "Apple A10 Fusion",
    sensors:
      "Accelerometer, Proximity, Gyroscope, Compass, Barometer, Touch ID",
    sim: "Nano-SIM",
  },
  {
    id: "16",
    name: "iPhone 8",
    year: 2017,
    screenSize: "4.7 inches",
    imageUrl: require("./assets/8.jpeg"),
    imageUrl1: require("./assets/second/7.jpeg"),
    storage: "64GB, 128GB",
    color: "Gold, Silver, Space Gray, Red",
    chip: "Apple A11 Bionic",
    sensors:
      "Accelerometer, Proximity, Gyroscope, Compass, Barometer, Touch ID",
    sim: "Nano-SIM",
  },
  {
    id: "17",
    name: "iPhone 8 Plus",
    year: 2017,
    screenSize: "5.5 inches",
    imageUrl: require("./assets/8plus.jpeg"),
    imageUrl1: require("./assets/second/7.jpeg"),
    storage: "64GB, 128GB",
    color: "Gold, Silver, Space Gray, Red",
    chip: "Apple A11 Bionic",
    sensors:
      "Accelerometer, Proximity, Gyroscope, Compass, Barometer, Touch ID",
    sim: "Nano-SIM",
  },
  {
    id: "18",
    name: "iPhone X",
    year: 2017,
    screenSize: "5.8 inches",
    imageUrl: require("./assets/x.jpeg"),
    imageUrl1: require("./assets/second/x.webp"),
    storage: "64GB, 256GB",
    color: "Silver, Space Gray",
    chip: "Apple A11 Bionic",
    sensors: "Accelerometer, Proximity, Gyroscope, Compass, Barometer, Face ID",
    sim: "Nano-SIM",
  },
  {
    id: "19",
    name: "iPhone XR",
    year: 2018,
    screenSize: "6.1 inches",
    imageUrl: require("./assets/xr.jpeg"),
    imageUrl1: require("./assets/second/x.webp"),
    storage: "64GB, 128GB, 256GB",
    color: "Black, White, Blue, Yellow, Coral, Red",
    chip: "Apple A12 Bionic",
    sensors: "Accelerometer, Proximity, Gyroscope, Compass, Barometer, Face ID",
    sim: "Nano-SIM and eSIM",
  },
  {
    id: "20",
    name: "iPhone XS",
    year: 2018,
    screenSize: "5.8 inches",
    imageUrl: require("./assets/xs.jpeg"),
    imageUrl1: require("./assets/second/x.webp"),
    storage: "64GB, 256GB, 512GB",
    color: "Gold, Silver, Space Gray",
    chip: "Apple A12 Bionic",
    sensors: "Accelerometer, Proximity, Gyroscope, Compass, Barometer, Face ID",
    sim: "Nano-SIM and eSIM",
  },
  {
    id: "21",
    name: "iPhone XS Max",
    year: 2018,
    screenSize: "6.5 inches",
    imageUrl: require("./assets/xs-max.jpeg"),
    imageUrl1: require("./assets/second/x.webp"),
    storage: "64GB, 256GB, 512GB",
    color: "Gold, Silver, Space Gray",
    chip: "Apple A12 Bionic",
    sensors: "Accelerometer, Proximity, Gyroscope, Compass, Barometer, Face ID",
    sim: "Nano-SIM and eSIM",
  },
  {
    id: "22",
    name: "iPhone 11",
    year: 2019,
    screenSize: "6.1 inches",
    imageUrl: require("./assets/11.jpeg"),
    imageUrl1: require("./assets/second/11.webp"),
    storage: "64GB, 128GB, 256GB",
    color: "Black, Green, Yellow, Purple, Red, White",
    chip: "Apple A13 Bionic",
    sensors: "Accelerometer, Proximity, Gyroscope, Compass, Barometer, Face ID",
    sim: "Dual SIM (Nano-SIM and eSIM)",
  },
  {
    id: "23",
    name: "iPhone 11 Pro",
    year: 2019,
    screenSize: "5.8 inches",
    imageUrl: require("./assets/11pro.jpeg"),
    imageUrl1: require("./assets/second/11.webp"),
    storage: "64GB, 256GB, 512GB",
    color: "Gold, Space Gray, Silver, Midnight Green",
    chip: "Apple A13 Bionic",
    sensors: "Accelerometer, Proximity, Gyroscope, Compass, Barometer, Face ID",
    sim: "Dual SIM (Nano-SIM and eSIM)",
  },
  {
    id: "24",
    name: "iPhone 11 Pro Max",
    year: 2019,
    screenSize: "6.5 inches",
    imageUrl: require("./assets/11promax.jpeg"),
    imageUrl1: require("./assets/second/11.webp"),
    storage: "64GB, 256GB, 512GB",
    color: "Gold, Space Gray, Silver, Midnight Green",
    chip: "Apple A13 Bionic",
    sensors: "Accelerometer, Proximity, Gyroscope, Compass, Barometer, Face ID",
    sim: "Dual SIM (Nano-SIM and eSIM)",
  },
  {
    id: "25",
    name: "iPhone SE (2nd generation)",
    year: 2020,
    screenSize: "4.7 inches",
    imageUrl: require("./assets/se2.jpeg"),
    imageUrl1: require("./assets/second/7.jpeg"),
    storage: "64GB, 128GB, 256GB",
    color: "Black, White, Red",
    chip: "Apple A13 Bionic",
    sensors:
      "Accelerometer, Proximity, Gyroscope, Compass, Barometer, Touch ID",
    sim: "Nano-SIM and eSIM",
  },
  {
    id: "26",
    name: "iPhone 12 Mini",
    year: 2020,
    screenSize: "5.4 inches",
    imageUrl: require("./assets/12mini.jpeg"),
    imageUrl1: require("./assets/second/12.jpeg"),
    storage: "64GB, 128GB, 256GB",
    color: "Black, White, Red, Green, Blue",
    chip: "Apple A14 Bionic",
    sensors: "Accelerometer, Proximity, Gyroscope, Compass, Barometer, Face ID",
    sim: "Dual SIM (Nano-SIM and eSIM)",
  },
  {
    id: "27",
    name: "iPhone 12",
    year: 2020,
    screenSize: "6.1 inches",
    imageUrl: require("./assets/12.jpeg"),
    imageUrl1: require("./assets/second/12.jpeg"),
    storage: "64GB, 128GB, 256GB",
    color: "Black, White, Red, Green, Blue",
    chip: "Apple A14 Bionic",
    sensors: "Accelerometer, Proximity, Gyroscope, Compass, Barometer, Face ID",
    sim: "Dual SIM (Nano-SIM and eSIM)",
  },
  {
    id: "28",
    name: "iPhone 12 Pro",
    year: 2020,
    screenSize: "6.1 inches",
    imageUrl: require("./assets/12pro.jpeg"),
    imageUrl1: require("./assets/second/12p.jpeg"),
    storage: "128GB, 256GB, 512GB",
    color: "Graphite, Silver, Gold, Pacific Blue",
    chip: "Apple A14 Bionic",
    sensors: "Accelerometer, Proximity, Gyroscope, Compass, Barometer, Face ID",
    sim: "Dual SIM (Nano-SIM and eSIM)",
  },
  {
    id: "29",
    name: "iPhone 12 Pro Max",
    year: 2020,
    screenSize: "6.7 inches",
    imageUrl: require("./assets/12promax.jpeg"),
    imageUrl1: require("./assets/second/12p.jpeg"),
    storage: "128GB, 256GB, 512GB",
    color: "Graphite, Silver, Gold, Pacific Blue",
    chip: "Apple A14 Bionic",
    sensors: "Accelerometer, Proximity, Gyroscope, Compass, Barometer, Face ID",
    sim: "Dual SIM (Nano-SIM and eSIM)",
  },
  {
    id: "30",
    name: "iPhone 13 Mini",
    year: 2021,
    screenSize: "5.4 inches",
    imageUrl: require("./assets/13mini.jpeg"),
    imageUrl1: require("./assets/second/13.webp"),
    storage: "128GB, 256GB, 512GB",
    color: "Pink, Blue, Midnight, Starlight, Product(RED)",
    chip: "Apple A15 Bionic",
    sensors: "Accelerometer, Proximity, Gyroscope, Compass, Barometer, Face ID",
    sim: "Dual SIM (Nano-SIM and eSIM)",
  },
  {
    id: "31",
    name: "iPhone 13",
    year: 2021,
    screenSize: "6.1 inches",
    imageUrl: require("./assets/13.jpeg"),
    imageUrl1: require("./assets/second/13.webp"),
    storage: "128GB, 256GB, 512GB",
    color: "Pink, Blue, Midnight, Starlight, Product(RED)",
    chip: "Apple A15 Bionic",
    sensors: "Accelerometer, Proximity, Gyroscope, Compass, Barometer, Face ID",
    sim: "Dual SIM (Nano-SIM and eSIM)",
  },
  {
    id: "32",
    name: "iPhone 13 Pro",
    year: 2021,
    screenSize: "6.1 inches",
    imageUrl: require("./assets/13pro.jpeg"),
    imageUrl1: require("./assets/second/13p.jpg"),
    storage: "128GB, 256GB, 512GB, 1TB",
    color: "Graphite, Gold, Silver, Sierra Blue",
    chip: "Apple A15 Bionic",
    sensors: "Accelerometer, Proximity, Gyroscope, Compass, Barometer, Face ID",
    sim: "Dual SIM (Nano-SIM and eSIM)",
  },
  {
    id: "33",
    name: "iPhone 13 Pro Max",
    year: 2021,
    screenSize: "6.7 inches",
    imageUrl: require("./assets/13promax.jpeg"),
    imageUrl1: require("./assets/second/13p.jpg"),
    storage: "128GB, 256GB, 512GB, 1TB",
    color: "Graphite, Gold, Silver, Sierra Blue",
    chip: "Apple A15 Bionic",
    sensors: "Accelerometer, Proximity, Gyroscope, Compass, Barometer, Face ID",
    sim: "Dual SIM (Nano-SIM and eSIM)",
  },
  {
    id: "34",
    name: "iPhone 14",
    year: 2022,
    screenSize: "6.1 inches",
    imageUrl: require("./assets/14.jpeg"),
    imageUrl1: require("./assets/second/14.jpg"),
    storage: "128GB, 256GB, 512GB",
    color: "Space Gray, Silver, Gold, Midnight",
    chip: "Apple A16 Bionic",
    sensors: "Face ID, Accelerometer, Proximity, Gyroscope, Compass",
    sim: "Dual SIM (Nano-SIM and eSIM)",
  },
  {
    id: "35",
    name: "iPhone 14 Pro",
    year: 2022,
    screenSize: "6.1 inches",
    imageUrl: require("./assets/14pro.jpeg"),
    imageUrl1: require("./assets/second/14p.jpeg"),
    storage: "128GB, 256GB, 512GB, 1TB",
    color: "Graphite, Silver, Gold, Sierra Blue",
    chip: "Apple A16 Bionic",
    sensors: "Face ID, Accelerometer, Proximity, Gyroscope, Compass",
    sim: "Dual SIM (Nano-SIM and eSIM)",
  },
  {
    id: "36",
    name: "iPhone 14 Plus",
    year: 2022,
    screenSize: "6.1 inches",
    imageUrl: require("./assets/14plus.jpeg"),
    imageUrl1: require("./assets/second/14.jpg"),
    storage: "128GB, 256GB, 512GB, 1TB",
    color: "Graphite, Silver, Gold, Sierra Blue",
    chip: "Apple A16 Bionic",
    sensors: "Face ID, Accelerometer, Proximity, Gyroscope, Compass",
    sim: "Dual SIM (Nano-SIM and eSIM)",
  },
  {
    id: "37",
    name: "iPhone 14 Pro Max",
    year: 2022,
    screenSize: "6.7 inches",
    imageUrl: require("./assets/14promax.jpeg"),
    imageUrl1: require("./assets/second/14p.jpeg"),
    storage: "128GB, 256GB, 512GB, 1TB",
    color: "Graphite, Silver, Gold, Sierra Blue",
    chip: "Apple A16 Bionic",
    sensors: "Face ID, Accelerometer, Proximity, Gyroscope, Compass",
    sim: "Dual SIM (Nano-SIM and eSIM)",
  },
];
