export const DeviceInfos = [
  {
    id: "1",
    name: "iPhone (original)",
    year: 2007,
    screenSize: "3.5 inches",
    imageUrl: require("./assets/original.jpeg"),
  },
  {
    id: "2",
    name: "iPhone 3G",
    year: 2008,
    screenSize: "3.5 inches",
    imageUrl: require("./assets/3g.jpeg"),
  },
  {
    id: "3",
    name: "iPhone 3GS",
    year: 2009,
    screenSize: "3.5 inches",
    imageUrl: require("./assets/3gs.jpeg"),
  },
  {
    id: "4",
    name: "iPhone 4",
    year: 2010,
    screenSize: "3.5 inches",
    imageUrl: require("./assets/4.jpeg"),
  },
  {
    id: "5",
    name: "iPhone 4s",
    year: 2011,
    screenSize: "3.5 inches",
    imageUrl: require("./assets/4s.jpeg"),
  },
  {
    id: "6",
    name: "iPhone 5",
    year: 2012,
    screenSize: "4 inches",
    imageUrl: require("./assets/5.jpeg"),
  },
  {
    id: "7",
    name: "iPhone 5c",
    year: 2013,
    screenSize: "4 inches",
    imageUrl: require("./assets/5c.jpeg"),
  },
  {
    id: "8",
    name: "iPhone 5s",
    year: 2013,
    screenSize: "4 inches",
    imageUrl: require("./assets/5s.jpeg"),
  },
  {
    id: "9",
    name: "iPhone 6",
    year: 2014,
    screenSize: "4.7 inches",
    imageUrl: require("./assets/6.jpeg"),
  },
  {
    id: "10",
    name: "iPhone 6 Plus",
    year: 2014,
    screenSize: "5.5 inches",
    imageUrl: require("./assets/6plus.jpeg"),
  },
  {
    id: "11",
    name: "iPhone 6s",
    year: 2015,
    screenSize: "4.7 inches",
    imageUrl: require("./assets/6s.jpeg"),
  },
  {
    id: "12",
    name: "iPhone 6s Plus",
    year: 2015,
    screenSize: "5.5 inches",
    imageUrl: require("./assets/6splus.jpeg"),
  },
  {
    id: "13",
    name: "iPhone SE ",
    year: 2016,
    screenSize: "4 inches",
    imageUrl: require("./assets/se1.jpeg"),
  },
  {
    id: "14",
    name: "iPhone 7",
    year: 2016,
    screenSize: "4.7 inches",
    imageUrl: require("./assets/7.jpeg"),
  },
  {
    id: "15",
    name: "iPhone 7 Plus",
    year: 2016,
    screenSize: "5.5 inches",
    imageUrl: require("./assets/7plus.jpeg"),
  },
  {
    id: "16",
    name: "iPhone 8",
    year: 2017,
    screenSize: "4.7 inches",
    imageUrl: require("./assets/8.jpeg"),
  },
  {
    id: "17",
    name: "iPhone 8 Plus",
    year: 2017,
    screenSize: "5.5 inches",
    imageUrl: require("./assets/8plus.jpeg"),
  },
  {
    id: "18",
    name: "iPhone X",
    year: 2017,
    screenSize: "5.8 inches",
    imageUrl: require("./assets/x.jpeg"),
  },
  {
    id: "19",
    name: "iPhone XR",
    year: 2018,
    screenSize: "6.1 inches",
    imageUrl: require("./assets/xr.jpeg"),
  },
  {
    id: "20",
    name: "iPhone XS",
    year: 2018,
    screenSize: "5.8 inches",
    imageUrl: require("./assets/xs.jpeg"),
  },
  {
    id: "21",
    name: "iPhone XS Max",
    year: 2018,
    screenSize: "6.5 inches",
    imageUrl: require("./assets/xs-max.jpeg"),
  },
  {
    id: "22",
    name: "iPhone 11",
    year: 2019,
    screenSize: "6.1 inches",
    imageUrl: require("./assets/11.jpeg"),
  },
  {
    id: "23",
    name: "iPhone 11 Pro",
    year: 2019,
    screenSize: "5.8 inches",
    imageUrl: require("./assets/11pro.jpeg"),
  },
  {
    id: "24",
    name: "iPhone 11 Pro Max",
    year: 2019,
    screenSize: "6.5 inches",
    imageUrl: require("./assets/11promax.jpeg"),
  },
  {
    id: "25",
    name: "iPhone SE (2)",
    year: 2020,
    screenSize: "4.7 inches",
    imageUrl: require("./assets/se2.jpeg"),
  },
  {
    id: "26",
    name: "iPhone 12 mini",
    year: 2020,
    screenSize: "5.4 inches",
    imageUrl: require("./assets/12mini.jpeg"),
  },
  {
    id: "27",
    name: "iPhone 12",
    year: 2020,
    screenSize: "6.1 inches",
    imageUrl: require("./assets/12.jpeg"),
  },
  {
    id: "28",
    name: "iPhone 12 Pro",
    year: 2020,
    screenSize: "6.1 inches",
    imageUrl: require("./assets/12pro.jpeg"),
  },
  {
    id: "29",
    name: "iPhone 12 Pro Max",
    year: 2020,
    screenSize: "6.7 inches",
    imageUrl: require("./assets/12promax.jpeg"),
  },
  {
    id: "30",
    name: "iPhone 13 mini",
    year: 2021,
    screenSize: "5.4 inches",
    imageUrl: require("./assets/13mini.jpeg"),
  },
  {
    id: "31",
    name: "iPhone 13",
    year: 2021,
    screenSize: "6.1 inches",
    imageUrl: require("./assets/13.jpeg"),
  },
  {
    id: "32",
    name: "iPhone 13 Pro",
    year: 2021,
    screenSize: "6.1 inches",
    imageUrl: require("./assets/13pro.jpeg"),
  },
  {
    id: "33",
    name: "iPhone 13 Pro Max",
    year: 2021,
    screenSize: "6.7 inches",
    imageUrl: require("./assets/13promax.jpeg"),
  },
  {
    id: "34",
    name: "iPhone 14",
    year: 2022,
    screenSize: "6.1 inches",
    imageUrl: require("./assets/14.jpeg"),
  },
  {
    id: "35",
    name: "iPhone 14 Pro",
    year: 2022,
    screenSize: "6.1 inches",
    imageUrl: require("./assets/14pro.jpeg"),
  },
  {
    id: "36",
    name: "iPhone 14 Plus",
    year: 2022,
    screenSize: "6.1 inches",
    imageUrl: require("./assets/14plus.jpeg"),
  },
  {
    id: "37",
    name: "iPhone 14 Pro Max",
    year: 2022,
    screenSize: "6.7 inches",
    imageUrl: require("./assets/14promax.jpeg"),
  },
];
